{% set name = "dpdata" %}
{% set version = "0.2.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepmodeling/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: ce2522f30320dee8744039f58d7830da8255c89286f1846538644674c010823f

build:
  number: 0
  noarch: python
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - numpy >=1.14.3
    - monty
    - scipy
    - h5py
    - wcmatch

test:
  requires:
    - python {{ python_min }}
  imports:
    - dpdata

about:
  home: https://github.com/deepmodeling/dpdata
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Manipulating DeePMD-kit, VASP and LAMMPS data formats
  doc_url: https://github.com/deepmodeling/dpdata
  dev_url: https://github.com/deepmodeling/dpdata

extra:
  recipe-maintainers:
    - njzjz
