{% set name = "dpdata" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepmodeling/{{ name }}/archive/{{ version }}.tar.gz
  sha256: ef8e471ebbf169b30d6083cfb960745807155987bfb8f89f8b61be8f474856a2

build:
  number: 0
  noarch: python
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools_scm
  run:
    - python >=3.5
    - numpy >=1.14.3
    - monty
    - scipy

test:
  imports:
    - dpdata

about:
  home: https://github.com/deepmodeling/dpdata
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Manipulating DeePMD-kit, VASP and LAMMPS data formats
  doc_url: https://github.com/deepmodeling/dpdata
  dev_url: https://github.com/deepmodeling/dpdata

extra:
  recipe-maintainers:
    - njzjz
